# Generated by Django 5.2.4 on 2025-08-16 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurringtransaction',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
    ]
