# Generated by Django 5.2.4 on 2025-08-17 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0002_remove_recurringtransaction_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recurringtransaction',
            old_name='start_date',
            new_name='date',
        ),
        migrations.AddField(
            model_name='recurringtransaction',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cash_flow.bankaccount'),
        ),
    ]
