# Generated by Django 5.2.4 on 2025-10-18 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0003_rename_start_date_recurringtransaction_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='tags',
        ),
        migrations.AlterUniqueTogether(
            name='creditcardinvoice',
            unique_together={('credit_card', 'due_date')},
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transfer_id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='credit_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='cash_flow.creditcard'),
        ),
        migrations.AlterField(
            model_name='recurringtransaction',
            name='type',
            field=models.CharField(choices=[(1, 'Pix'), (2, 'Cash'), (3, 'Credit Card')], max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[(1, 'Pix'), (2, 'Cash'), (3, 'Credit Card')], max_length=10),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.RemoveField(
            model_name='creditcardinvoice',
            name='month',
        ),
        migrations.RemoveField(
            model_name='creditcardinvoice',
            name='year',
        ),
    ]
