# Generated by Django 5.2.4 on 2025-10-18 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0004_remove_transaction_tags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditcard',
            name='user',
        ),
        migrations.AddField(
            model_name='creditcardinvoice',
            name='closing_date',
            field=models.DateField(default='2025-10-01'),
            preserve_default=False,
        ),
    ]
