# Generated by Django 5.2.4 on 2025-10-27 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0005_remove_creditcard_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='type',
        ),
        migrations.AlterField(
            model_name='recurringtransaction',
            name='type',
            field=models.CharField(choices=[('PIX', 'Pix'), ('CASH', 'Cash'), ('CREDITCARD', 'Credit Card')], max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('PIX', 'Pix'), ('CASH', 'Cash'), ('CREDITCARD', 'Credit Card')], max_length=12),
        ),
    ]
