# Generated by Django 5.2.4 on 2025-10-27 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0006_remove_category_type_alter_recurringtransaction_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
